service:
  name: aa-datalake

provider:
  name: aws
  profile: aa
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-northeast-2'}
  runtime: nodejs12.x
  memorySize: 128
  logRetentionInDays: 7
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchGetItem
        - dynamodb:BatchWriteItem
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:DescribeStream
        - dynamodb:ListStreams
      Resource: "arn:aws:dynamodb:ap-northeast-2:*:*"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "arn:aws:lambda:ap-northeast-2:*:*"
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:GetBucketLocation
        - s3:ListBucket
        - s3:ListBucketMultipartUploads
        - s3:ListMultipartUploadParts
        - s3:AbortMultipartUpload
        - s3:CreateBucket
      Resource: "arn:aws:s3:::*"
  environment: ${file(./env.${self:provider.stage}.yml)}

package:
  indivisually: true

plugins:
  - serverless-jetpack
  - serverless-webpack

functions:
  cronGetAbandonedAnimals:
    description: "유기동물 데이터 크롤링"
    handler: cron/getAbandonedAnimalsPerHour.handler
    memorySize: 256
    timeout: 60
    environment:
      TZ: Asia/Seoul
    events:
      - schedule:
          name: ${opt:stage}-cron-aa-raw-data-weekdays-peak
          description: '유기동물 데이터를 가져온다, 평일 피크'
          rate: cron(0/10 0-9 * * MON-FRI *)
      - schedule:
          name: ${opt:stage}-cron-aa-raw-data-weekdays
          description: '유기동물 데이터를 가져온다, 평일 일반'
          rate: cron(0 10-23 * * MON-FRI *)
      - schedule:
          name: ${opt:stage}-cron-aa-raw-data-weekends
          description: '유기동물 데이터를 가져온다, 주말'
          rate: cron(0 0/4 * * SUN,SAT *)
