name: terraform-plan
on:
  push:
    paths:
      - 'terraform/*'
      - '.github/workflows/terraform-plan.yml'
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set credentials
        run: |
          aws configure set region ap-northeast-2
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws --profile aa configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws --profile aa configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: deploy development infrastructure
        run: |
          cd terraform
          terraform init
          terraform workspace select dev
          terraform plan
          cd -


